_layouts/reference.html
Tutorial index pages did not have a link to move user to the next section, making it confusing where to go once you select your tutorial level. 
I added links to these pages by editing reference.html to include the same code as tutorial.html to pull in links to the next pages.
=> Added next links on index pages

_layouts/home.html, docs/tutorials/getting-started/creating-your-first-project.md
I wanted to check out 2.0 a bit more so I was following the tutorial and notice the `apostrophe create` command has been changed to `apostrophe create-project`, but wasn't reflected in the docs. I updated the two places I found, hopefully this helps!
=> Updating docs to use the new create-project command of the CLI.

docs/tutorials/getting-started/schema-guide.md
Label and value were switched in the code example.
=> Fixed code example typos.

docs/tutorials/intermediate/cursors.md
cf.
http://apostrophecms.org/docs/modules/apostrophe-docs/index.html#get-manager
http://apostrophecms.org/docs/modules/apostrophe-doc-type-manager/index.html
=> Fix 2 typos in cursor code doc

README.md
Deploying required having the [sitemap-static](https://www.npmjs.com/package/sitemap-static) module installed. Added that to the deployment instructions.
=> Added note about installing sitemap-static

stylesheets/_content.less
Just ran across this minor issue where the sidebar in the documentation always shows scrollbars (even if the content doesn't actually overflow the height of the container). This is just a single line change - basically the same thing as https://github.com/apostrophecms/apostrophe/pull/1100
I have tested manually and confirmed that it works as expected!
=> Changed sidebar style from overflow: scroll to overflow: auto

tutorials/getting-started/schema-guide.md
See the `attachment` section here: https://apostrophecms.org/docs/tutorials/getting-started/schema-guide.html
=> Fixes link typo

technical-overviews/how-apostrophe-handles-requests.md
The "Dispatch: handling prefix URL matches with  apostrophe-custom-pages" example didn't extend the custom pages module.
=> Fixed a mistake in "how-apostrophe-handles-requests"

tutorials/howtos/ckeditor.md
The removeButtons config is now automatically altered depending on which buttons are specified in the template options' `toolbar` property, as per https://github.com/apostrophecms/apostrophe/pull/1779
=> Remove `config.removeButtons` example code

modules/apostrophe-pieces/index.md
Currently the apostrophe-pieces module docs ([link](https://apostrophecms.org/docs/modules/apostrophe-pieces/)) has two dead links to one of the tutorials. They lead to https://apostrophecms.org/docs/modules/tutorials/getting-started/reusable-content-with-pieces.html when they should lead to https://apostrophecms.org/docs/tutorials/getting-started/reusable-content-with-pieces.html
=> Fix tutorials link in apostrophe-pieces module docs

modules/apostrophe-module/README.md, modules/apostrophe-templates/README.md, tutorials/getting-started/reusable-content-with-pieces.md
=> replace typo in nunjuck templates `extend` > `extends`

tutorials/howtos/storing-sessions-in-redis.md
The links was: https://npmjs.org/packages/apostrophe-caches-redis (this is 404)
Now is: https://npmjs.org/package/apostrophe-caches-redis
;)
=> Extra s on the last link url

modules/apostrophe-module/README.md
This seemed worth documenting to make clear how these arguments from the `emit` method are used in the event handler.
=> Specifies the usage of  arguments

tutorials/getting-started/schema-guide.md
=> Fixed documentation typo

tutorials/core-concepts/reusable-content-pieces/joins.md
When going through the pieces tutorial, I couldn't get this one example to work. I looked through the open-museum demo and it seems like you do things like `{% set artist = data.piece._artist %}`. I'm assuming `{% set person = data.piece %}` and `{% if person._job %}` would follow your development style more closely, but simply changing `data.person` to `data.piece` works and keeps this whole document consistent.
Also, a massive thank you to the Apostrophe team for everything you do!
=> Joins example fix

tutorials/advanced-development/how-apostrophe-starts-up.md
✏️ It is a typo fix in line 28 `Node that` to `Note that`.
=> typo fix 'Node that' to 'Note that'

docs/core-concepts/working-with-templates/nunjucks-helper-functions.md
No `addFilters` function in `apostrophe/lib/modules/apostrophe-templates` but  `addFilter` instead
=> Fix `addFilter` command in Nunjucks helpers

docs/core-concepts/editable-content-on-pages/standard-widgets.md
Closes #39. Not adding a tutorial, but the docs in apos-attachments are pretty good already. We also don't want to be confusing, suggesting there is a different tutorial that will cover more.
=> Rephrases custom image size reference

docs/.vuepress/sidebar.json
A few of the groups had abnormal default states. Those are smoothed out. There's still an odd case with the Devops due to an odd choice in Vuepress to make the first child group of a section open by default. It comes into play a few other times in sub-sections as well.
=> Makes sidebar behavior more consistent

docs/advanced-topics/promise-events/promise-events.md
Overriding an existing promise event handler, the example given has a slight syntax error, a trailing closing brackets.
=> Remove the trailing Closing brackets

docs/advanced-topics/advanced-pieces-topics/overriding-piece-urls.md
Properly retrieve the `piece`'s slug used in external site's url.
=> Fix: piece url pointing to external site.

docs/advanced-topics/how-apostrophe-handles-requests.md
Correct the mistyped `server` method of `apostrophe-pages` to `serve`.
=> Fix: `serve` method for `apostrophe-pages`

docs/reference/field-types/joinbyarrayreverse.md, docs/reference/field-types/joinbyonereverse.md
Removes options from reverse join documentation that refer to UI (it has no UI).
=> Removes UI options from reverse join fields

docs/advanced-topics/database/cursors.md
As per https://docs.apostrophecms.org/reference/modules/apostrophe-docs/server-apostrophe-cursor.html#methods. the self.get should get the nameOfFilter. In this case the name of the filter is busy. Unless I misunderstood it.
=> self.get('nameOfFilter')

docs/.vuepress/config.js
Because of the URL changes Algolia search is indexing is bringing up nothing. Reverting to the heading search for now.
=> Disables Algolia deep search
