apostrophecms/apostrophe-documentation

docs/tutorials/howtos/docker.md, docs/tutorials/howtos/index.md
Per punkave/apostrophe-boilerplate#4
=> Add Docker howto

docs/tutorials/getting-started/creating-your-first-project.md
It may be unclear for a new user when logging in what the username is of the account they just created. I added a couple words on the Creating a New Project documentation clarifying the username is "admin."
=> Clarified admin login on tutorial

_layouts/default.html, _layouts/home.html, _layouts/layout.html, index.md, stylesheets/_content.less, stylesheets/_footer.less, stylesheets/_header.less, stylesheets/_nav.less, stylesheets/_structure.less
These are some initial styles to make the docs responsive.
Some stuff isn't completely perfect yet, but for the most part the site is now accessible on phones.
#34
=> Responsive styles

docs/tutorials/getting-started/editing-page-templates.md
They are still 2 old Nunjucks URLs. This PR replaces them with the new homepage URL.
=> Fix remnants of Nunjucks old homepage URL

docs/tutorials/intermediate/cursors.md
Removing this note after adding it as an issue (#60).
=> Removed TODO after adding as an Issue.

docs/tutorials/intermediate/cursors.md
=> Fix typo in cursors example

tutorials/howtos/ckeditor.md
This should resolve [issue#72](https://github.com/punkave/apostrophe-documentation/issues/72) but I can't publish the changes to the live site
=> resolve broken link

tutorials/howtos/ckeditor.md
Removes what seems like a typo in the allowed elements.
=> Removes typo element.

docs/tutorials/howtos/deploying-apostrophe-in-the-cloud.md
I went through the deploying with Heroku tutorial, and it pretty much worked fine! Just a couple of things I thought could be clarified.
=> clarified heroku docs, fixes #42

tutorials/howtos/index.md, tutorials/howtos/trim-index.md
Adds directions and example for removing specific pieces from an index listing.
=> Adds howto for trimming index pieces

tutorials/howtos/trim-index.md
Fixes syntax highlighting on tutorial.
=> Enables syntax highlighting

package-lock.json, tutorials/getting-started/adding-editable-content-to-pages.md
I had trouble finding this myself simply by searching.
=> Easier access to custom image info

tutorials/getting-started/pushing-assets.md
I had some trouble getting web-fonts and images to work that weren't uploaded by users, so I wanted to submit some quick documentation to hopefully prevent any issues for others in the future.
=> Document usage of assets other than css / js

tutorials/getting-started/settings.md
fixed the markdown so the javascript code appears correctly as code in the website
=> Update settings.md - fixed markdown

modules/apostrophe-caches/index.md
=> Adds documentation for cache tasks

tutorials/getting-started/creating-your-first-project.md
I think new users will appreciate an alternative to `node app.js` after every file change.
What do you think? I am not a native speaker, so feel free to correct me where possible.
=> Added Nodemon as alternative way to (re)start the app

tutorials/getting-started/schema-guide.md
This is pending approval and merge of [PR #1529](https://github.com/apostrophecms/apostrophe/pull/1529).
=> Update documentation for date field

tutorials/howtos/responsive-images.md
=> Improve language in responsive images how-to

tutorials/howtos/deploying-apostrophe-in-the-cloud-with-heroku.md
Added tip for resolving CORS issue when using heroku and AWS
=> added CORS ERROR tip for Heroku with AWS

technical-overviews/how-apostrophe-handles-requests.md
=> Fixed Documentation for how-apostrophe-handles-requests

tutorials/howtos/docker.md
Added docker-compose example, update to include the important APOS_ALWAYS_COPY_ASSETS ENV variable for containerised Apos.
=> Docker config additional information

tutorials/howtos/docker.md
Incorrect that docker creates environment variable for you
=> Clarification of db environment variable

tutorials/getting-started/schema-guide.md
Related to the update in https://github.com/apostrophecms/apostrophe/pull/1915
=> Adds note about htmlHelp schema property

other/nunjucks-filters.md
=> Adds link to momentJS formatting docs

tutorials/getting-started/reusable-content-with-pieces.md
Way more hints than I anticipated... Best to go commit by commit.
=> Closes parens and clarifies filter docs

README.md, tutorials/advanced-development/advanced-pieces-topics/suppressing-pieces.md
Fixed weird link and missing file
=> Fixes from testing on docs

tutorials/advanced-development/database/model-layer.md
I have added the options parameter
=> fix beforeSave method documentation

.gitbook.yaml, tutorials/advanced-development/database/custom-schema-field-types.md
I made some tweaks, and currently all of the identified links are working on my test site. There was also one misplaced file in the repo which has been corrected.
=> Fix for final bad links

tutorials/core-concepts/editable-content-on-pages/layout-widgets.md
=> Add missing closing %}

tutorials/core-concepts/reusable-content-pieces/displaying-pieces-with-widgets.md
=> Update file refs

tutorials/advanced-development/advanced-pieces-topics/README.md
Broke on https://docs.apostrophecms.org/apostrophe/advanced-topics/advanced-pieces-topics.
=> Fixes section TOC link

_api-reference-generator/package-lock.json, _api-reference-generator/package.json, modules/apostrophe-areas/browser-apostrophe-areas-editor.md, modules/apostrophe-areas/browser-apostrophe-areas.md, modules/apostrophe-docs/README.md, modules/apostrophe-login/README.md, modules/apostrophe-pages/README.md, modules/apostrophe-users/README.md, modules/apostrophe-widgets/README.md
Generates the documentation for the latest Apostrophe version.
=> Runs the generate script for v2.102.2

tutorials/getting-started/creating-your-first-project.md
This PR proposes to fix "autmoatically" typo to expected "automatically".
=> Fix "autmoatically" typo

deploy, package.json
Deploy script for Vuepress docs. Currently only set for staging.
=> Vuepress deploy

_api-reference-generator/package.json, _tip-ins/modules.md, docs/reference/modules/apostrophe-assets/README.md, docs/reference/modules/apostrophe-docs/README.md, docs/reference/modules/apostrophe-images/README.md, docs/reference/modules/apostrophe-login/README.md, docs/reference/modules/apostrophe-pages/README.md, docs/reference/modules/apostrophe-pieces/README.md, docs/reference/modules/apostrophe-ui/README.md, docs/reference/modules/apostrophe-utils/README.md, docs/reference/modules/apostrophe-widgets/README.md, package.json
Updates from the latest published version of Apostrophe core, with other updates for ongoing module docs generation.
=> Vuefix core updates

docs/.vuepress/enhanceApp.js
=> Fixes wildcard redirects

HOW_TO_UPDATE_THE_DOCUMENTATION.md, docs/.vuepress/config.js, docs/README.md, docs/getting-started/README.md, docs/getting-started/contribution.md
We're consolidating around the .com. Forum and chat will be next.
=> Switches to the dot com for demo and docs

docs/.vuepress/theme/components/GithubStars.vue, docs/.vuepress/theme/components/Sidebar.vue
Adds the Github star widget
The second commit is the only new code.
=> Star widget

docs/reference/field-types/date.md
=> Removes the outdated line about date needing def:null

docs/advanced-topics/advanced-pieces-topics/adding-columns.md
=> Fixes an error in the add-columns page

docs/.vuepress/config.js
Docs ref: https://v1.vuepress.vuejs.org/config/#head
=> Adds hubspot script

docs/getting-started/creating-your-first-project.md
I think this has come up a few times. It's worth clarifying that the boilerplate is only for the codebase.
=> Clarifies how boilerplates work

docs/howtos/ckeditor.md
I am also asking Rakhi to take a look at this PR herself before we merge it.
=> Notes from Rakhi on how to get the icon to work for a ckeditor plugin that comes from the ckeditor team but is missing from our theme

docs/core-concepts/editable-content-on-pages/custom-widgets.md, docs/core-concepts/modules/how-apostrophe-modules-are-structured.md, docs/core-concepts/pages-and-navigation/page-templates.md, docs/howtos/ckeditor.md
Adds additional notes on installing CKEditor plugins.
=> Ckeditor plugin

docs/core-concepts/pages-and-navigation/connecting-pages.md
=> Fixes spelling of Yggdrasill

docs/howtos/docker.md
=> Minor typo fix

docs/advanced-topics/promise-events/promise-events.md
Add async keyword on  asynchronous function example given, otherwise, you will get a SyntaxError: await is only valid in an async function
=> Add async keyword on asynchronous function

docs/getting-started/setting-up-your-environment.md
This based on the instructions following brew install.
=> Updates the Mongodb service command

docs/core-concepts/front-end-assets/pushing-assets.md
Broken at https://docs.apostrophecms.org/core-concepts/front-end-assets/pushing-assets.html#pushing-stylesheets-and-javascript-from-your-own-modules
=> Fixes broken anchor link

docs/advanced-topics/advanced-pieces-topics/adding-columns.md
I saw this solution answered by @boutell in SO. I couldn't understand this part of the docs, so adding in a bit of context for how to use the partial method with joins.
=> Clarify partial method for joins

_api-reference-generator/package-lock.json, docs/core-concepts/editable-content-on-pages/standard-widgets.md
Documents the default style improvement from https://github.com/apostrophecms/apostrophe/pull/2641
=> Documents default style in rich text widget

_api-reference-generator/package-lock.json, _api-reference-generator/package.json, docs/reference/modules/apostrophe-docs/README.md, docs/reference/modules/apostrophe-pages/README.md, docs/reference/modules/apostrophe-pieces/README.md
=> Updates docs for 2.116.1

docs/.vuepress/sidebar.json
🤦 This page wasn't in the navigation for some reason.
=> Adds migrations page to the sidebar

package-lock.json, package.json
Resolves one vulnerability warning.
=> Updates vuepress

docs/.vuepress/sidebar.json, docs/devops/deployment/README.md, docs/devops/deployment/deploying-apostrophe-in-the-cloud-with-aws.md, docs/devops/deployment/deploying-apostrophe-in-the-cloud-with-heroku.md, docs/devops/deployment/deployment.md, docs/reference/modules/apostrophe-oembed/README.md, docs/reference/modules/apostrophe-users/README.md
Fixes typos and out of date content in the deployment section
=> Deployment updates

docs/core-concepts/reusable-content-pieces/browsing-directory-of-pieces.md, docs/core-concepts/reusable-content-pieces/joins.md
=> Fixes typos

docs/core-concepts/reusable-content-pieces/joins.md
Hello, i found an error, if you follow the guide, when you come to this point you can't access 'data.person' because it's undefined.
Instead of accesing 'data.person' you can acces 'data.piece' and do the rigth stuff.
=> Bug fix when following the guide

docs/reference/field-types/video.md
A question came up about how to use this, so I thought it would help to more explicitly direct people to the video widget.
=> Adds note about video field intention

docs/.vuepress/config.js
*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*
Changes the relative file linking of the favicon images. Works locally. Hopefully, this will fix the favicon not showing up in production.
*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly
????
1. Deploy to production.
2. Navigate to the site and look for the favicon.
3. 
*(Check at least one)*
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval …
=> Add favicon

docs/getting-started/creating-your-first-project.md, docs/getting-started/setting-up-your-environment.md
Closes issue PRO-3105. Added --a2 flag to the start project guide. Also included a quick note of which version of Node to have installed. 
*For example:*
> 1. Basically just added the flag and the node version note, so just make sure in the right spot. should be good. 
*(Check at least one)*
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.
**Other information:**
=> PRO-3105 - added --a2 flag to start project
